### ISSUE TITLE
Mosquitto container log volume permission issue

### ISSUE THREAD

**Issue by Habilya** [gcgarner/IOTstack#108]
Hello, I've just discovered an issue with the Mosquitto container's log volume  issue

My Raspberry Pi 3 Docker was installed through the docker sh installer script provided from Docker.
It runs under root user on my Raspberry Pi, which is probably not a good thing... but will have to do for now.

So, the issue is with the mosquitto container as it cannot start properly.
with this logged error

```
1575308247: Error: Unable to open log file /mosquitto/log/mosquitto.log for writing.
```

I've done quick checkups
`ls -la` the volumes, it's owned by root:root

Then, I've checked the service.yml
`cat services/mosquitto/service.yml`

```
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: unless-stopped
    user: "1883"
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./volumes/mosquitto/data:/mosquitto/data
      - ./volumes/mosquitto/log:/mosquitto/log
      - ./services/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
```

This line caught my attention `user: "1883"`

Therefore, "dirty fixed" it using such commands

```
sudo touch volumes/mosquitto/log/mosquitto.log
sudo chmod o+w volumes/mosquitto/log/mosquitto.log
sudo chown 1883:1883 volumes/mosquitto/log -R
```

and restarted the container.

Please advise?
