### ISSUE TITLE
Feature request: add deConz to stack

### ISSUE THREAD

**Issue by DIYtechie** [gcgarner/IOTstack#145]
Please consider adding deConz to the IOT stack: https://hub.docker.com/r/marthoc/deconz

A natural part of a basic IOT stack for those not using zigbee2mqtt.

These are good default settings (ConBee II hardware, VNC enabled, less cluttered port):

```
  deconz:
    image: marthoc/deconz
    container_name: deconz
    restart: unless-stopped
    network_mode: bridge
    ports:
      - '80:80'
      - '443:443'
      - '5901:5900'
    volumes:
       - ./volumes/deconz/:/root/.local/share/dresden-elektronik/deCONZ
    devices:
      #ConBee II:
      - /dev/ttyACM0
      #ConBee:
      # - /dev/ttyUSB0
      #RaspBee: 
      # - /dev/ttyAMA0 or /dev/ttyS0
    environment:
      - DECONZ_VNC_MODE=1
      - DECONZ_VNC_PASSWORD=changeme
      - DEBUG_INFO=1
      - DEBUG_APS=0
      - DEBUG_ZCL=0
      - DEBUG_ZDP=0
      - DEBUG_OTAU=0
```
