### ISSUE TITLE
Error in docker-compose with telegraf config entry

### ISSUE THREAD

**Issue by GarryG** [gcgarner/IOTstack#207]
Hi,

I just tried out IOTstack and it's great ... except for one small problem - I keep getting errors when I try to use telegraf ...

```
root@raspi4:~/IOTstack# docker-compose up -d
ERROR: yaml.parser.ParserError: while parsing a block mapping
  in "./docker-compose.yml", line 68, column 5
expected <block end>, but found '<block sequence start>'
  in "./docker-compose.yml", line 75, column 7

```
Line 68 is the first "container_name: telegraf" line right after the "telegraf:" entry. If I move the whole block to somewhere else in the file, the error line moves; removing it lets docker-compose run through successfully, so it's definitely something in the telegraf block.

```
  telegraf:
    container_name: telegraf
    image: telegraf
    volumes:
      - ./services/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
          - cadvisor-arm
          - node-exporter
      - influxdb
      - mosquitto
```

The yaml file is used right out of the generation by menu.sh, nothing was originally edited or changed ...

Sorry, not really learned about yaml files, I reckon it's probably something minor ...
