### ISSUE TITLE
Unable to get ttyUSB* devices available in Home Assistant container

### ISSUE THREAD

**Issue by lnlp** [gcgarner/IOTstack#50]
My Home Assistant configuration is using two devices connected via USB (USB to Serial).
According to docker-compose documentation (https://docs.docker.com/compose/compose-file/) ttyUSB* host devices can be made available in a container via the 'devices:' option as follows:

```
 hassio:
    image: "homeassistant/home-assistant:latest"
    container_name: "hassio"
    restart: unless-stopped
    network_mode: "host"
    #depends_on:
    #  - influxdb
    #  - mosquitto
    ports:
      - 8123:8123
    volumes:
      - ./volumes/hassio/config:/config
      - /etc/localtime:/etc/localtime:ro
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
      - "/dev/ttyUSB1:/dev/ttyUSB1"
```
I have tried using both with and without the surrounding double quotes but both without success.
_(I restarted the stack both times after updating docker-compose.yml and hassio service.yml.)_

My Home Assistance setup is configured to use /dev/ttyUSB0 and /dev/ttyUSB1 and home-assistant.log shows that files /dev/ttyUSB0 and /dev/ttyUSB1 do not exist.
_(This was not an issue previously when my Home Assistant was not running in a container.)_

When opening a terminal to the hassio container (from within Portainer) and doing an `ls /dev`, the ttyUSB0 and ttyUSB1 devices are not visible (which is consistent with Home Assistant's error messages in the log).

**How can ttyUSB0 and ttyUSB1 be made available in the Home Assistant container?**

_(It would be useful to add this information to the IOTstack documentation.)_
