### ISSUE TITLE
MotionEye

### ISSUE THREAD

**Issue by Slyke** [gcgarner/IOTstack#76]
I use MotionEye on my Raspberry Pi 3 as a front door security system, but it's not exactly IoT.

Would you mind if I submitted a PR to add it to the list of things you have here? Won't go to the trouble if it's not wanted :).

I currently have a working docker-compose file that "just runs out of the box":

```
version: '3'

services:
  motion_eye:
    image: "ccrisan/motioneye:master-armhf" #This needs to be changed to "ccrisan/motioneye:master-amd64" for non RPis
    container_name: "motion_eye"
    restart: unless-stopped
    ports:
      - 80:8765 #WUI, change these to work with your reverse proxy
      - 8081:8081 #Streaming (Video0)
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/motioneye:/etc/motioneye
      - /var/lib/motioneye:/var/lib/motioneye
    devices:
      - "/dev/video0:/dev/video0" #This is for the camera on the CSI interface. Not sure if USB cams will be added as video0 if CSI is not connected. It may just put the first camera if finds as video0
```
