### ISSUE TITLE
mosquitto container restarting

### ISSUE THREAD

**Issue by DaniWahl** [gcgarner/IOTstack#77]
Hi Graham
Congratulation and many thanks for this great tool and it's excellent description. 
I installed IOTstack on my raspi today and learned a lot about Docker thanks to this. 

I have realized that the Mosquitto container keeps restarting all the time. The container log shows the following errors:
`Error: Unable to open log file /mosquitto/log/mosquitto.log for writing.`
I even created the log file myself but no success. 

I found [here](https://github.com/eclipse/mosquitto/issues/1078)
that mosquitto wants its files to me owned by the UID 1883, independent whether a user with that UID exists or not. 

I changed the file ownership like this:
`sudo chown -R 1883:1883 ~/IOTstack/volumes/mosquitto`
and restarted the container. 
Mosquitto runs fine after this.

I think this is a bug from mosquitto, but maybe someone finds this helpful.

**Comment by gcgarner** [comment]
Hi Dani

I changes the volume mappings in the template and they didnt work as intented

I've changed them back to this not to affect anyone else (besides you now that you did the chown)
```
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto
    restart: unless-stopped
    user: "0"
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - ./volumes/mosquitto/:/mosquitto/
      - ./services/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
```
