### ISSUE TITLE
Node-Red Serial port?

### ISSUE THREAD

**Issue by crossband** [gcgarner/IOTstack#80]
Dear All,

I have grafana, influxdb, mosquitto, nodered and portainer installed on Raspberry Pi 4, everything seems to be running. Node-Red GUI is also accessible on port 1880.

But I can not get the local serial port to work.  Serial device is definitely working, I have checked it using `screen /dev/ttyUSB0 115200` command. But it shows "not connected" in GUI.

Node-Red commands like `node-red-stop` are also do not work.

Did I perhaps something wrong? I have installed it following the IOTstack instructions, using `./menu.sh`.

![image](https://user-images.githubusercontent.com/20731500/69039821-fa084800-09ec-11ea-8401-08206ba18bbe.png)

**Comment by gcgarner** [comment]
@crossband docker containers are placed in a sandbox and cannot access system hardware unless explicitly told to do so. I haven't 'enabled' the serial device by default, because I haven't had the opportunity to test it yet.

I've got a usb serial device lying around in a drawer somewhere, I'll try to get it working by Friday. There are some hoops with rights and the dialout group. That functionally I would need to build into the stack script

node-red-stop will not work when executing from the Pi's terminal. The sandbox concept means for all intents and purposed the nodered container is separate machine. Therefore you would need to access its terminal (like using ssh) to run commands against that container.

The preferred way of stopping and starting containers is via the docker command. You can type `docker stop nodered` and `docker start nodered` to stop and start them

**Comment by gcgarner** [comment]
I did a quick test and i was able to connect to the serial port, would you mind testing the following for me? edit you docker-compose.yml file and under nodered insert the privileged key

```
  nodered:
    container_name: nodered
    build: ./services/nodered/.
    restart: unless-stopped
    user: "0"
    privileged: true
    ports:
      - 1880:1880
    volumes:
      - ./volumes/nodered/data:/data
```
i can connect to my serial port but i've got nothing to talk to at the moment. I'd appreciate if you could test and let me know then i can update the project to reflect the changes


![image](https://user-images.githubusercontent.com/46672225/69045255-2dec6900-09ff-11ea-8784-5f981892c633.png)

**Comment by gcgarner** [comment]
I forgot to add you will need to run `docker-compose up -d` from the IOTstack folder to restart nodered with the changes

**Comment by crossband** [comment]
Thanks Graham for your prompt reply. It worked!
Now docker-compose.yml file looks like this:
```
version: '2'
services:
  nodered:
    container_name: nodered
    build: ./services/nodered/.
    restart: unless-stopped
    user: "0"
    privileged: true
    ports:
      - 1880:1880
    volumes:
      - ./volumes/nodered/data:/data
```
